#Write a program to input 8 numbers from the user and display all the unique numbers (once)
s = set()
n = int(input("enter number 1"))
s.add(n)
n = int(input("enter number 2"))
s.add(n)
n = int(input("enter number 3"))
s.add(n)
n = int(input("enter number 4"))
s.add(n)
n = int(input("enter number 5"))
s.add(n)
n = int(input("enter number 6"))
s.add(n)
n = int(input("enter number 7"))
s.add(n)
n = int(input("enter number 8"))
s.add(n)
print(s)
